# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='notification_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
